### ISSUE TITLE
An error will occur when use dataset 'mrc'(GR-SP10)

### ISSUE THREAD

**Issue by larry6799** [BUserName/PMGN#1]
Hello, your code I run uses the data set you provide.
However, when running the task of text to text classification（GR-SP10）, there was an error and a wrong report was reported：
![微信截图_20210419170038](https://user-images.githubusercontent.com/29395892/115210882-9b8b5000-a131-11eb-820c-45ca55bdef14.png)
The code on the other dataset tasks is running normally.

**Comment by BUserName** [comment]
Hi Larry,

Thanks for your interest in our work and brought up this issue! I have just checked the code and the error can be changed by modifying line 204 of data_loader.py  from
`self.target_ratio = self.num_class - target_ratio`
to 
```
if self.num_class - target_ratio > 0: 
            self.target_ratio = self.num_class - target_ratio
else:
            self.target_ratio=0
```
This should not affect the final results of PMGN though. Please feel free to let me know if you have any other concerns.

You can also reach me at zijian.wang at uq.edu.au
